spring.application.name=tetProject

server.port=1010

#MYSQL CONNECTION
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER_NAME}
spring.datasource.password=${DATABASE_USER_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 2. Driver & Hibernate Settings
## PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# Email Config details
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_EMAIL_ID}
spring.mail.password=${SPRING_EMAIL_APP_PASSWORD}

# Add these lines to fix the [EOF] / Bad Greeting error
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true